config:
  url: @configServer@
spring:
  application:
    name: registry-server
  profiles:
    default: @activatedProperties@
  cloud:
    config:
      fail-fast: true
      password: BdEwu2023
      username: admin
  config:
    import: configserver:${config.url}
  main:
    allow-circular-references: true

  security:
    user:
      name: admin
      password: BdEwu2023

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
