version: '3.9'

services:
  lims-mysql:
    container_name: lims-mysql
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'lims'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'lims'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - /var/lib/mysql/lims-db:/var/lib/mysql
      - ./docker/mysql/init/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./docker/mysql/init/data.sql:/docker-entrypoint-initdb.d/2.sql


  lims-redis:
    container_name: lims-redis
    image: redis:latest
    restart: always
    command: redis-server --requirepass redis
    ports:
      - '6379:6379'
    expose:
      - '6379'
    volumes:
      - /var/lib/redis/lims-db:/data
