server:
  port: 8080
  forward-headers-strategy: framework

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://admin:BdEwu2023@localhost:8082/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        add-to-simple-url-handler-mapping: true
      routes:
        - id: authorization-server
          uri: http://localhost:8083
          predicates:
            - Path=/authorization/**
          filters:
            - RewritePath=/authorization/(?<path>.*), /$\{path}

        - id: user-service
          uri: http://localhost:8090
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}

        - id: utility-service
          uri: http://localhost:8091
          predicates:
            - Path=/utility/**
          filters:
            - RewritePath=/utility/(?<path>.*), /$\{path}