server:
  port: 8080
  forward-headers-strategy: framework

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        add-to-simple-url-handler-mapping: true
      routes:
        - id: user-service
          uri: http://localhost:8090
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}

        - id: utility-service
          uri: http://localhost:8091
          predicates:
            - Path=/utility/**
          filters:
            - RewritePath=/utility/(?<path>.*), /$\{path}
