config:
  url: @configServer@
spring:
  application:
    name: utility-service
  profiles:
    active: @activatedProperties@
  cloud:
    config:
      fail-fast: true
      password: BdEwu2023
      username: admin
  config:
    import: configserver:${config.url}
  main:
    allow-circular-references: true
