spring:
  cloud:
    config:
      fail-fast: false
      server:
        native:
          search-locations:
            - classpath:/config
            - classpath:config/{application}
            - classpath:config/{profile}/{application}
  profiles:
    active: native
  security:
    user:
      name: admin
      password: BdEwu2023

server:
  port: 8081
  forward-headers-strategy: framework